<?php

$degrees = array(
'Bachelor of Architecture',
'Bachelor of Biomedical Science',
'Bachelor of Business Administration',
'Bachelor of Clinical Science',
'Bachelor of Commerce',
'Bachelor of Computer Information Systems',
'BS Construction Technology',
'Bachelor of Criminal Justice',
'Bachelor of Divinity',
'Bachelor of Economics',
'Bachelor of Education',
'Bachelor of Engineering',
'Bachelor of Fine Arts',
'Bachelor of Information Systems',
'Bachelor of Management',
'Bachelor of Music',
'Bachelor of Pharmacy',
'Bachelor of Philosophy',
'Bachelor of Social Work',
'Bachelor of Accountancy',
'BA American Studies',
'BA American Indian Studies',
'BA Applied Psychology',
'BA Biology',
'BA Anthropology',
'BA Child Advocacy',
'BA Clinical Psychology',
'BA Forensic Psychology',
'BA Organizational Psychology',
'BS Aerospace Engineering',
'BS Actuarial',
'BS Agriculture',
'BS Architecture',
'BS Architectural Engineering',
'BS Biology',
'BS Biomedical Engineering',
'BS Business Administration',
'BS Chemical Engineering',
'BS Chemistry',
'BS Civil Engineering',
'BS Clinical Laboratory Science',
'BS Cognitive Science',
'BS Computer Engineering',
'BS Computer Science',
'BS Construction Engineering',
'BS Construction Management',
'BS Criminal Justice',
'BS Criminology',
'BS Diagnostic Radiography',
'BS Education',
'BS Electrical Engineering',
'BS Engineering Physics',
'BS Engineering Science',
'BS Engineering Technology',
'BS English Literature',
'BS Environmental Engineering',
'BS Environmental Science',
'BS Environmental Studies',
'BS Food Science',
'BS Foreign Service',
'BS Forensic Science',
'BS Forestry',
'BS History',
'BS Hospitality Management',
'BS Human Resources Management',
'BS Industrial Engineering',
'BS Information Technology',
'BS Information Systems',
'BS Integrated Science, Business and Technology',
'BS International Relations',
'BS Journalism',
'BS Management',
'BS Manufacturing Engineering',
'BS Marketing',
'BS Mathematics',
'BS Mechanical Engineering',
'BS Medical Technology',
'BS Meteorology',
'BS Microbiology',
'BS Mining Engineering',
'BS Molecular Biology',
'BS Neuroscience',
'BS Nursing',
'BS Nutrition science',
'BS Software Engineering',
'BS Petroleum Engineering',
'BS Podiatry',
'BS Pharmacology',
'BS Pharmacy',
'BS Physical Therapy',
'BS Physics',
'BS Plant Science',
'BS Politics',
'BS Psychology',
'BS Quantity Surveying Engineering',
'BS Radiologic Technology',
'BS Real-Time Interactive Simulation',
'BS Religion',
'BS Respiratory Therapy',
'BS Risk Management and Insurance',
'BS Science Education',
'BS Systems Engineering',
'BM Jazz Studies',
'BM Composition',
'BM Performance',
'BM Theory',
'BM Music Education',
'Bachelor of Sports Management',
);